import { useCallback, useEffect, useRef, useState } from 'react';
import { ArrowDownToLine, ArrowLeft, ArrowRight, Check, CheckCheck, ChevronRight, CircleAlert, Clapperboard, Clock3, Code2, FileCheck2, Film, FolderOpen, GitBranch, History, ImagePlus, Layers3, LoaderCircle, Play, Plus, RefreshCw, Send, Settings2, ShieldCheck, Sparkles, Square, Upload, X } from 'lucide-react';
import type { Case, Job, Project, Report } from '../core/schema.ts';
import { api, seconds, time } from './api.ts';
import { Player, type MediaMap } from './Player.tsx';
import { RoomArt } from './RoomArt.tsx';

type View='overview'|'script'|'shots'|'checks'|'history';
type FullProject=Project&{assetStates:{id:string;current:boolean}[]};
const tabs:[View,string,typeof Film][]=[['overview','作品概览',Layers3],['script','剧本与证据',GitBranch],['shots','场景与分镜',Clapperboard],['checks','检查与修复',ShieldCheck],['history','版本记录',History]];
const initialBrief='暴雨封山的旧旅馆里，一卷即将公映的胶片不见了。设计三个各怀秘密的成年嫌疑人，玩家通过搜证与盘问找回胶片，最后揭开一个温柔的真相。';
function mediaMap(p:FullProject):MediaMap {const map:MediaMap={};for(const a of p.assets)if(p.assetStates.find(s=>s.id===a.id)?.current)(map[a.sceneId]??={})[a.kind]=`/media/${a.file}`;return map;}

export default function App(){
  const [projects,setProjects]=useState<any[]>([]),[project,setProject]=useState<FullProject|null>(null),[view,setView]=useState<View>('overview');
  const [status,setStatus]=useState<any>(null),[jobs,setJobs]=useState<Job[]>([]),[activeJob,setActiveJob]=useState<string|null>(null);
  const [brief,setBrief]=useState(initialBrief),[creating,setCreating]=useState(false),[playing,setPlaying]=useState(false),[toast,setToast]=useState(''),[busy,setBusy]=useState(false);
  const opened=useRef(new Set<string>());
  const refreshProjects=useCallback(async()=>setProjects(await api('/projects')),[]);
  const load=useCallback(async(id:string)=>{setProject(await api(`/projects/${id}`));},[]);
  useEffect(()=>{void refreshProjects().catch(e=>setToast(e.message));void api('/status').then(setStatus).catch(()=>{});const timer=setInterval(()=>void api('/status').then(setStatus).catch(()=>{}),20000);return()=>clearInterval(timer);},[refreshProjects]);
  useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),6500);return()=>clearTimeout(t);},[toast]);
  useEffect(()=>{let mounted=true;const poll=async()=>{try{const list=await api<Job[]>('/jobs');if(!mounted)return;setJobs(list);const job=list.find(j=>j.id===activeJob);if(job&&['succeeded','failed','cancelled'].includes(job.state)&&!opened.current.has(job.id)){opened.current.add(job.id);if(job.projectId)await load(job.projectId);await refreshProjects();setToast(job.state==='succeeded'?'任务完成，已保存产物。':job.error||'任务已停止。');}}catch{}};void poll();const t=setInterval(poll,2200);return()=>{mounted=false;clearInterval(t);};},[activeJob,load,refreshProjects]);
  async function attempt(fn:()=>Promise<void>){setBusy(true);try{await fn();}catch(e){setToast((e as Error).message);}finally{setBusy(false);}}
  async function sample(){await attempt(async()=>{const p=await api<Project>('/projects/sample','POST',{});await load(p.id);await refreshProjects();setView('overview');});}
  async function generate(){await attempt(async()=>{const job=await api<Job>('/generate','POST',{prompt:brief});setActiveJob(job.id);setCreating(false);setToast('案件创作已加入队列，可在制作记录中查看进展。');});}
  async function importJson(file:File){await attempt(async()=>{const body=JSON.parse(await file.text());const p=await api('/projects/import','POST',body);await load(p.id);await refreshProjects();});}
  async function runAgent(kind:'edit'|'repair',prompt:string){if(!project)return;await attempt(async()=>{const j=await api<Job>(`/projects/${project.id}/agent`,'POST',{kind,prompt});setActiveJob(j.id);});}
  async function save(doc:Case,note='手动编辑案件'){if(!project)return;await attempt(async()=>{await api(`/projects/${project.id}/case`,'PUT',{case:doc,baseRevision:project.revision,note});await load(project.id);await refreshProjects();setToast('新版本已保存，检查结果已更新。');});}
  async function check(){if(!project)return;await attempt(async()=>{await api(`/projects/${project.id}/validate`,'POST',{});await load(project.id);setView('checks');});}
  const job=jobs.find(j=>j.id===activeJob)??jobs.find(j=>j.projectId===project?.id);
  const active=job&&['running','queued'].includes(job.state);
  const media=project?mediaMap(project):{};
  if(playing&&project)return <Player key={`${project.id}-${project.revision}`} doc={project.case} media={media} onExit={()=>setPlaying(false)}/>;
  return <div className="app-shell">
    <aside className="sidebar"><button className="brand" onClick={()=>setProject(null)}><span className="brand-icon"><Clapperboard size={22}/></span><span>幕间<small>MUJIAN STUDIO</small></span></button><p className="workspace-label">推理影游创作工坊</p><button className={`side-item ${!project?'active':''}`} onClick={()=>setProject(null)}><FolderOpen size={17}/>我的作品<span>{projects.length}</span></button><div className="side-divider"/>{project&&<><div className="side-project-name">{project.title}</div>{tabs.map(([id,label,Icon])=><button key={id} className={`side-item ${view===id?'active':''}`} onClick={()=>setView(id)}><Icon size={17}/>{label}{id==='checks'&&project.report&&!project.report.passed&&<i className="error-dot"/>}</button>)}</>}<div className="sidebar-bottom"><div className="spark-mark"><span className={`status-dot ${status?.llm?.reachable?'online':''}`}/><div><strong>{status?.media?.gpu||'DGX Spark 工作空间'}</strong><small>{status?.llm?.reachable?'创作模型已连接':'等待连接创作模型'}</small></div></div><p>创作发生在这里，<br/>故事可以去任何地方。</p><span className="version-label">Pi Agent · 本地优先</span></div></aside>
    <div className="workspace"><header className="topbar"><div className="breadcrumb"><span>工作空间</span><ChevronRight size={13}/><strong>{project?.title||'我的作品'}</strong>{project&&<span className="revision-tag">v{project.revision}</span>}</div><div className="top-actions">{project?<><button className="secondary" onClick={()=>setPlaying(true)}><Play size={14}/>试玩</button><a className={`primary compact ${!project.report?.passed?'disabled':''}`} href={`/api/projects/${project.id}/export`} title={!project.report?.passed?'请先修复规则错误':'导出包含素材的独立 HTML'}><ArrowDownToLine size={15}/>导出作品</a></>:<button className="primary compact" onClick={()=>setCreating(true)}><Plus size={15}/>新建作品</button>}</div></header>
    <div className={`workspace-body ${project?'with-agent':''}`}><main className="main-content">
      {!project?<><section className="welcome-hero"><div className="welcome-text"><span className="eyebrow">从一段悬念，到一部可玩的故事</span><h1>让你的故事，<br/><em>发生在选择之间。</em></h1><p>写下灵感，让 Agent 编排案件、制作分镜、检查证据链。<br/>每一个选择，都通往你设计的真相。</p><div className="button-row"><button className="primary" onClick={()=>setCreating(true)}><Sparkles size={17}/>开始创作</button><button className="secondary" onClick={sample} disabled={busy}>体验示例<ArrowRight size={16}/></button></div><span className="hero-caption">示例为原创手写案件 · 生成任务使用已连接的模型</span></div><div className="welcome-art"><RoomArt/><div className="floating-slate"><span>TAKE 01</span><strong>雨停之前</strong><p>3 个场景 / 3 位嫌疑人 / 2 个结局</p></div></div></section><div className="section-heading"><div><span className="eyebrow">你的创作空间</span><h2>继续一个故事</h2></div><label className="subtle file-label"><Upload size={15}/>导入案件 JSON<input type="file" accept=".json,application/json" onChange={e=>e.target.files?.[0]&&void importJson(e.target.files[0])}/></label></div>{projects.length?<div className="project-grid">{projects.map(p=><button className="project-card" key={p.id} onClick={()=>{void load(p.id);setView('overview');}}><div className="project-cover"><RoomArt/><span>{p.source==='sample'?'手写示例':p.source==='generated'?'Agent 创作':'导入作品'}</span></div><div className="project-card-info"><h3>{p.title}<ArrowRight size={16}/></h3><p>{p.logline}</p><div><span>{p.scenes} 场景 · v{p.revision}</span><span>{time(p.updatedAt)}</span></div></div></button>)}</div>:<div className="empty-projects"><Film size={26}/><div><strong>第一部作品，从一个“如果”开始</strong><p>也可以先打开《雨停之前》，亲手找出案件的真相。</p></div></div>}{job&&<div className="home-job"><AgentPanel job={job} project={null} onRun={runAgent} onCancel={()=>void api(`/jobs/${job.id}/cancel`,'POST',{}).catch(e=>setToast(e.message))}/></div>}</>:
      <>
      {view==='overview'&&<><div className="page-heading"><div><span className="eyebrow">PROJECT OVERVIEW</span><h1>{project.title}</h1><p>{project.case.logline}</p></div><span className={`pill ${project.report?.passed?'success':'warning'}`}>{project.report?.passed?<CheckCheck size={14}/>:<CircleAlert size={14}/>} {project.report?.passed?'规则检查通过':'需要检查规则'}</span></div><div className="overview-cover">{media[project.case.scenes[0].id]?.image?<img src={media[project.case.scenes[0].id].image} alt="作品场景"/>:<RoomArt scene={project.case.scenes[0].id}/>}<div className="cover-overlay"><span>INTERACTIVE MYSTERY · 原创短篇</span><h2>{project.title}</h2><button className="play-circle" onClick={()=>setPlaying(true)} aria-label="开始试玩"><Play size={24} fill="currentColor"/></button><p>搜寻细节，问出隐情。真相藏在你的下一步里。</p></div></div><div className="stat-grid">{[[project.case.scenes.length,'可探索场景'],[project.case.characters.length,'案件人物'],[project.case.clues.length,'证据与证词'],[project.case.endings.length,'剧情结局']].map(([n,label])=><div key={label}><strong>{n}</strong><span>{label}</span></div>)}</div><div className="overview-bottom"><section className="panel"><div className="section-heading"><h3>故事开场</h3><button className="subtle" onClick={()=>setView('script')}>编辑剧本<ArrowRight size={14}/></button></div><p className="opening-text">{project.case.opening}</p><div className="cast-strip">{project.case.characters.map(c=><div key={c.id}><span className="avatar">{c.name.slice(-2)}</span><div><strong>{c.name}</strong><small>{c.role}</small></div></div>)}</div></section><section className="panel progress-panel"><h3>交付前的三件事</h3><button onClick={()=>setView('script')}><span className="number-circle">1</span><div><strong>审阅人物与真相</strong><small>让动机与线索站得住脚</small></div><ChevronRight size={15}/></button><button onClick={()=>setView('shots')}><span className="number-circle">2</span><div><strong>为场景制作镜头</strong><small>{project.assets.length} 份素材已保存</small></div><ChevronRight size={15}/></button><button onClick={check}><span className="number-circle">3</span><div><strong>走通证据链</strong><small>{project.report?.passed?'已找到可回放的结案路径':'检查角色与证据的依赖'}</small></div><ChevronRight size={15}/></button></section></div></>}
      {view==='script'&&<ScriptEditor project={project} onSave={save} busy={busy}/>}
      {view==='shots'&&<Shots project={project} media={media} onJob={j=>setActiveJob(j.id)} onRefresh={()=>load(project.id)} onError={setToast}/>}
      {view==='checks'&&<Checks project={project} onCheck={check} onRepair={()=>runAgent('repair','修复检查器发现的所有规则错误，保持案件真相、结案所需证据和主要剧情不变。')} onInject={()=>{const doc=structuredClone(project.case);const clue=doc.clues.find(c=>c.sceneId&&doc.truth.requiredEvidenceIds.includes(c.id));if(clue){clue.requires=[...new Set([...clue.requires,clue.id])];void save(doc,'演示：明确注入关键证据自依赖');}}} busy={busy||!!active}/>}
      {view==='history'&&<><div className="page-heading"><div><span className="eyebrow">PROJECT HISTORY</span><h1>每一步，都可以回看。</h1><p>恢复旧版会创建新版本，已有记录和素材继续保留。</p></div><a className="secondary" href={`/api/projects/${project.id}/json`}><Code2 size={15}/>下载案件 JSON</a></div><div className="history-list">{[...project.revisions].reverse().map(r=><article className="panel" key={r.id}><span className="revision-badge">v{r.number}</span><div><h3>{r.note}</h3><p>{time(r.createdAt)} · {r.case.title}</p><code>{r.hash.slice(0,16)}</code></div>{r.number===project.revision?<span className="pill success">当前版本</span>:<button className="secondary" onClick={()=>attempt(async()=>{await api(`/projects/${project.id}/restore`,'POST',{revision:r.number});await load(project.id);setToast(`已恢复第 ${r.number} 版的内容。`);})}><History size={14}/>恢复此版</button>}</article>)}</div></>}
      </>}
    </main>{project&&<AgentPanel project={project} job={job} onRun={runAgent} onCancel={()=>job&&void api(`/jobs/${job.id}/cancel`,'POST',{}).catch(e=>setToast(e.message))}/>}</div></div>
    {creating&&<div className="modal-backdrop"><div className="modal create-modal"><button className="close-button" onClick={()=>setCreating(false)} aria-label="关闭"><X size={20}/></button><span className="eyebrow">NEW STORY</span><h2>先给故事一个悬念。</h2><p className="muted">描述发生了什么、故事的气质，以及你希望玩家发现什么。</p><textarea aria-label="故事创意" value={brief} onChange={e=>setBrief(e.target.value)} rows={6}/><div className="prompt-chips"><button onClick={()=>setBrief(initialBrief)}>雨夜失窃</button><button onClick={()=>setBrief('在一座即将闭馆的海边天文台，一块陨石样本被调包。三个成年研究者都有动机，关键在于观测日志与潮汐时间不一致。请制作证据充足、温暖结尾的短篇推理游戏。')}>天文台谜案</button></div><div className="creation-spec"><span>3 名人物</span><span>3 个场景</span><span>6 条证据</span><span>可独立导出</span></div><p className="muted">先生成可玩的案件。图片和视频可在分镜页按需制作。</p><button className="primary wide" disabled={busy||brief.trim().length<5} onClick={generate}>{busy?<LoaderCircle className="spin" size={17}/>:<Sparkles size={17}/>}开始编排案件</button></div></div>}
    {toast&&<div className="toast" role="status"><CircleAlert size={17}/><span>{toast}</span><button onClick={()=>setToast('')} aria-label="关闭提示"><X size={14}/></button></div>}
  </div>;
}

function AgentPanel({project,job,onRun,onCancel}:{project:Project|null;job?:Job;onRun:(kind:'edit'|'repair',prompt:string)=>Promise<void>;onCancel:()=>void}){
  const [prompt,setPrompt]=useState('');const running=job&&['queued','running'].includes(job.state);
  const end=useRef<HTMLDivElement>(null);useEffect(()=>end.current?.scrollIntoView({block:'nearest'}),[job?.events.length]);
  const states={queued:'等待制作',running:'正在制作',succeeded:'已完成',failed:'任务失败',cancelled:'已取消',interrupted:'任务中断'};
  return <aside className="agent-panel"><div className="agent-heading"><span className="agent-logo"><Sparkles size={17}/></span><div><strong>创作搭档</strong><small>Pi Agent · 专业技能</small></div>{running&&<LoaderCircle size={16} className="spin"/>}</div><div className="agent-body">{!job?<><div className="agent-welcome"><span>让故事继续生长。</span><p>我可以修改角色、梳理线索，或修复走不通的剧情。每次编辑都会保留旧版。</p></div><div className="agent-suggestions">{['把故事的结尾改得更温暖，保持证据链完整。','检查人物在场证明与案件时间线是否矛盾。'].map(s=><button key={s} onClick={()=>setPrompt(s)}>{s}<ArrowRight size={13}/></button>)}</div></>:<><div className={`job-state ${job.state}`}><span className={running?'pulse-dot':'status-dot'}/><strong>{states[job.state]}</strong><small>{time(job.createdAt)}</small></div><div className="job-request">{String(job.request.prompt||`${job.kind==='image'?'图片':'视频'}生成 · ${job.request.sceneId}`)}</div><div className="event-list">{job.events.filter(e=>e.type!=='usage').map((e,i)=><div className={`event event-${e.type}`} key={`${i}-${e.at}`}><span className="event-dot"/><div><p>{e.message}</p>{e.type==='media'&&<small>已开始真实本地生成</small>}{e.type==='cache'&&<small>此次复用已有产物，未重新推理</small>}<time>{new Date(e.at).toLocaleTimeString('zh-CN')}</time></div></div>)}</div>{job.error&&<div className="inline-error">{job.error}</div>}{job.state==='succeeded'&&<div className="agent-complete"><CheckCheck size={17}/><p>产物已保存。建议继续试玩，确认故事与画面符合你的想法。</p></div>}<div ref={end}/></>}</div>{project&&<div className="agent-input"><label htmlFor="agent-prompt">你想调整哪里？</label><textarea id="agent-prompt" placeholder="例如：让摄影师先隐瞒目击证词，出示电源记录后才开口……" value={prompt} onChange={e=>setPrompt(e.target.value)} rows={4}/><div><small>修改后自动检查</small>{running?<button className="subtle" onClick={onCancel}><Square size={13}/>取消任务</button>:<button className="send-button" aria-label="发送修改要求" disabled={prompt.trim().length<3} onClick={()=>{void onRun('edit',prompt);setPrompt('');}}><Send size={15}/></button>}</div></div>}</aside>;
}

function Field({label,value,onChange,multiline=false,readOnly=false}:{label:string;value:string;onChange?:(s:string)=>void;multiline?:boolean;readOnly?:boolean}){
  return <label className="field"><span>{label}</span>{multiline?<textarea rows={3} value={value} readOnly={readOnly} onChange={e=>onChange?.(e.target.value)}/>:<input value={value} readOnly={readOnly} onChange={e=>onChange?.(e.target.value)}/>}</label>;
}
function EvidenceSelect({label,doc,value,onChange}:{label:string;doc:Case;value:string[];onChange:(v:string[])=>void}){return <fieldset className="evidence-select"><legend>{label}</legend>{doc.clues.map(c=><label key={c.id}><input type="checkbox" checked={value.includes(c.id)} onChange={()=>onChange(value.includes(c.id)?value.filter(id=>id!==c.id):[...value,c.id])}/>{c.name}</label>)}</fieldset>;}
function ScriptEditor({project,onSave,busy}:{project:Project;onSave:(doc:Case)=>Promise<void>;busy:boolean}){
  const [doc,setDoc]=useState<Case>(()=>structuredClone(project.case)),[section,setSection]=useState('scenes'),[selected,setSelected]=useState(0),[raw,setRaw]=useState(''),[error,setError]=useState('');
  useEffect(()=>{setDoc(structuredClone(project.case));setRaw(JSON.stringify(project.case,null,2));setSelected(0);},[project.id,project.revision]);
  const change=(fn:(d:Case)=>void)=>setDoc(old=>{const next=structuredClone(old);fn(next);return next;});
  const dirty=JSON.stringify(doc)!==JSON.stringify(project.case)||(section==='json'&&raw!==JSON.stringify(project.case,null,2));
  const scene=doc.scenes[Math.min(selected,doc.scenes.length-1)],char=doc.characters[Math.min(selected,doc.characters.length-1)],clue=doc.clues[Math.min(selected,doc.clues.length-1)];
  function save(){try{setError('');void onSave(section==='json'?JSON.parse(raw):doc);}catch{setError('JSON 格式不正确，请检查后重试。');}}
  return <><div className="page-heading"><div><span className="eyebrow">STORY BIBLE</span><h1>把每一条线索，写清楚。</h1><p>修改会创建新版本，并重新检查玩家是否能够完成案件。</p></div><button className="primary" disabled={!dirty||busy} onClick={save}>{busy?<LoaderCircle size={16} className="spin"/>:<Check size={16}/>}保存修改</button></div><div className="editor-tabs">{[['scenes','场景'],['characters','人物与对白'],['clues','证据'],['truth','作者真相'],['json','JSON']].map(([id,label])=><button className={section===id?'active':''} key={id} onClick={()=>{setSection(id);setSelected(0);if(id==='json')setRaw(JSON.stringify(doc,null,2));}}>{label}</button>)}{dirty&&<span>有未保存修改</span>}</div>{error&&<div className="inline-error">{error}</div>}
    {section==='json'?<textarea className="json-editor" aria-label="案件 JSON" spellCheck={false} value={raw} onChange={e=>setRaw(e.target.value)}/>:section==='truth'?<div className="panel editor-form"><div className="author-note"><CircleAlert size={17}/>以下是作者设定，试玩时不会直接展示。</div><Field label="作品名" value={doc.title} onChange={v=>change(d=>{d.title=v;})}/><Field label="故事简介" value={doc.logline} multiline onChange={v=>change(d=>{d.logline=v;})}/><Field label="开场" value={doc.opening} multiline onChange={v=>change(d=>{d.opening=v;})}/><label className="field"><span>案件责任人</span><select value={doc.truth.culpritId} onChange={e=>change(d=>{d.truth.culpritId=e.target.value;})}>{doc.characters.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><Field label="动机" value={doc.truth.motive} multiline onChange={v=>change(d=>{d.truth.motive=v;})}/><Field label="手法" value={doc.truth.method} multiline onChange={v=>change(d=>{d.truth.method=v;})}/><EvidenceSelect label="结案必须出示的证据" doc={doc} value={doc.truth.requiredEvidenceIds} onChange={v=>change(d=>{d.truth.requiredEvidenceIds=v;})}/><h3>真实时间线</h3>{doc.truth.timeline.map((t,i)=><div className="timeline-edit" key={i}><Field label="时间" value={t.time} onChange={v=>change(d=>{d.truth.timeline[i].time=v;})}/><Field label="发生了什么" value={t.event} onChange={v=>change(d=>{d.truth.timeline[i].event=v;})}/></div>)}{doc.endings.map((e,i)=><div key={e.id}><Field label={e.kind==='solved'?'正确结案标题':'错误结案标题'} value={e.title} onChange={v=>change(d=>{d.endings[i].title=v;})}/><Field label="结局文本" value={e.text} multiline onChange={v=>change(d=>{d.endings[i].text=v;})}/></div>)}</div>:<div className="editor-layout"><div className="entity-list">{(section==='scenes'?doc.scenes:section==='characters'?doc.characters:doc.clues).map((item,i)=><button className={i===selected?'active':''} key={item.id} onClick={()=>setSelected(i)}><span>{String(i+1).padStart(2,'0')}</span><div><strong>{item.name}</strong><small>{item.id}</small></div><ChevronRight size={14}/></button>)}</div><div className="panel editor-form">
      {section==='scenes'&&<><Field label="场景名称" value={scene.name} onChange={v=>change(d=>{d.scenes[selected].name=v;})}/><Field label="现场描述" value={scene.description} multiline onChange={v=>change(d=>{d.scenes[selected].description=v;})}/><EvidenceSelect label="进入前需要获得的证据（留空即开放）" doc={doc} value={scene.requires} onChange={v=>change(d=>{d.scenes[selected].requires=v;})}/><fieldset className="evidence-select"><legend>在场人物</legend>{doc.characters.map(c=><label key={c.id}><input type="checkbox" checked={scene.characterIds.includes(c.id)} onChange={()=>change(d=>{const s=d.scenes[selected];s.characterIds=s.characterIds.includes(c.id)?s.characterIds.filter(id=>id!==c.id):[...s.characterIds,c.id];})}/>{c.name}</label>)}</fieldset><Field label="场景图片提示" value={scene.imagePrompt} multiline onChange={v=>change(d=>{d.scenes[selected].imagePrompt=v;})}/><Field label="视频镜头提示" value={scene.videoPrompt} multiline onChange={v=>change(d=>{d.scenes[selected].videoPrompt=v;})}/></>}
      {section==='characters'&&<><div className="character-heading"><span className="avatar large">{char.name.slice(-2)}</span><div><h2>{char.name}</h2><p>{char.role}</p></div></div><Field label="姓名" value={char.name} onChange={v=>change(d=>{d.characters[selected].name=v;})}/><Field label="身份与年龄" value={char.role} onChange={v=>change(d=>{d.characters[selected].role=v;})}/><Field label="外观与服装" value={char.description} multiline onChange={v=>change(d=>{d.characters[selected].description=v;})}/><Field label="开场公开信息" value={char.publicKnowledge} multiline onChange={v=>change(d=>{d.characters[selected].publicKnowledge=v;})}/><Field label="隐瞒的信息（作者视角）" value={char.secret} multiline onChange={v=>change(d=>{d.characters[selected].secret=v;})}/><h3>分阶段问话</h3>{char.topics.map((t,i)=><details className="topic-editor" key={t.id} open={i===0}><summary>{t.question}</summary><Field label="玩家提问" value={t.question} onChange={v=>change(d=>{d.characters[selected].topics[i].question=v;})}/><Field label="固定回答" value={t.answer} multiline onChange={v=>change(d=>{d.characters[selected].topics[i].answer=v;})}/><EvidenceSelect label="出示这些证据后才可问" doc={doc} value={t.requires} onChange={v=>change(d=>{d.characters[selected].topics[i].requires=v;})}/><EvidenceSelect label="问话后获得的证词" doc={doc} value={t.reveals} onChange={v=>change(d=>{d.characters[selected].topics[i].reveals=v;})}/></details>)}</>}
      {section==='clues'&&<><Field label="证据名称" value={clue.name} onChange={v=>change(d=>{d.clues[selected].name=v;})}/><Field label="玩家看到的准确内容" value={clue.description} multiline onChange={v=>change(d=>{d.clues[selected].description=v;})}/><label className="field"><span>证据来源</span><select value={clue.sceneId||''} onChange={e=>change(d=>{d.clues[selected].sceneId=e.target.value||null;})}><option value="">通过人物问话获得</option>{doc.scenes.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><EvidenceSelect label="取得此证据前的条件" doc={doc} value={clue.requires} onChange={v=>change(d=>{d.clues[selected].requires=v;})}/><p className="muted">证据条件之间不能形成无法开始的循环。保存后会自动检查。</p></>}
    </div></div>}</>;
}

function Shots({project,media,onJob,onRefresh,onError}:{project:FullProject;media:MediaMap;onJob:(j:Job)=>void;onRefresh:()=>Promise<void>;onError:(s:string)=>void}){
  const [seed,setSeed]=useState(42),[quality,setQuality]=useState<'draft'|'final'>('draft');
  async function generate(sceneId:string,kind:'image'|'video'){try{onJob(await api(`/projects/${project.id}/media`,'POST',{sceneId,kind,seed,quality}));}catch(e){onError((e as Error).message);}}
  async function upload(sceneId:string,file:File){try{const r=await fetch(`/api/projects/${project.id}/upload/${sceneId}`,{method:'POST',headers:{'Content-Type':file.type},body:file});if(!r.ok)throw new Error((await r.json()).error);await onRefresh();}catch(e){onError((e as Error).message);}}
  return <><div className="page-heading"><div><span className="eyebrow">SHOT WORKSHOP</span><h1>先看见，再让它发生。</h1><p>先制作场景图片，再以图片作为视频首帧。相同输入复用已有素材。</p></div></div><div className="shot-settings"><Settings2 size={16}/><label>生成档位 <select value={quality} onChange={e=>setQuality(e.target.value as 'draft'|'final')}><option value="draft">草稿 · 768 × 448 / 约 2 秒</option><option value="final">正式 · 1280 × 704 / 约 5 秒</option></select></label><label>种子 <input aria-label="生成种子" type="number" min="0" max="2147483647" value={seed} onChange={e=>setSeed(Number(e.target.value))}/></label></div><div className="shot-grid">{project.case.scenes.map((s,i)=>{const assets=project.assets.filter(a=>a.sceneId===s.id);const latest=assets.at(-1);const stale=assets.some(a=>!project.assetStates.find(v=>v.id===a.id)?.current);return <article className="shot-card" key={s.id}><div className="shot-preview">{media[s.id]?.video?<video controls muted loop playsInline src={media[s.id].video} poster={media[s.id].image}/>:media[s.id]?.image?<img src={media[s.id].image} alt={s.name}/>:<RoomArt scene={s.id}/>}<span className="shot-number">SCENE {String(i+1).padStart(2,'0')}</span>{!media[s.id]&&<span className="art-label">示意插画</span>}</div><div className="shot-info"><h3>{s.name}{stale&&<span className="pill warning">含过期素材</span>}</h3><p>{s.description}</p><details><summary>查看镜头提示与生成记录</summary><p className="shot-prompt">{s.videoPrompt}</p>{assets.length?assets.map(a=><div className="asset-receipt" key={a.id}><a href={`/media/${a.file}`} target="_blank" rel="noreferrer">{a.kind==='image'?'图片':'视频'} · {a.provenance==='upload'?'手动导入':a.model.split('/').at(-1)}</a><small>{a.provenance==='upload'?'导入素材':seconds(a.durationMs)} · 种子 {a.seed} · {project.assetStates.find(v=>v.id===a.id)?.current?'当前可用':'已过期'}</small></div>):<p className="muted">还没有生成素材。</p>}</details><div className="shot-buttons"><button className="secondary" onClick={()=>generate(s.id,'image')}><ImagePlus size={14}/>制作图片</button><button className="primary compact" onClick={()=>generate(s.id,'video')}><Film size={14}/>制作视频</button><label className="icon-button file-label" title="导入场景图片"><Upload size={16}/><input aria-label={`导入${s.name}图片`} type="file" accept="image/png,image/jpeg" onChange={e=>e.target.files?.[0]&&void upload(s.id,e.target.files[0])}/></label></div>{latest&&<small className="muted">最近产物 {time(latest.createdAt)}</small>}</div></article>;})}</div><div className="info-note"><CircleAlert size={17}/><p>当前视频基线不含配音，角色跨镜头一致性需要逐镜审阅。画面中的物品与文字用于氛围，推理以游戏内的证据记录为准。</p></div></>;
}

function Checks({project,onCheck,onRepair,onInject,busy}:{project:Project;onCheck:()=>void;onRepair:()=>void;onInject:()=>void;busy:boolean}){
  const report=project.report;const errors=report?.issues.filter(i=>i.severity==='error')||[];
  const actionLabel=(a:Report['winningPath'][number])=>a.type==='travel'?`前往 ${project.case.scenes.find(s=>s.id===a.sceneId)?.name}`:a.type==='collect'?`取得 ${project.case.clues.find(c=>c.id===a.clueId)?.name}`:a.type==='ask'?`盘问 ${project.case.characters.find(c=>c.id===a.characterId)?.name}，获得证词`:'出示完整证据，正确结案';
  return <><div className="page-heading"><div><span className="eyebrow">PLAYABILITY CHECK</span><h1>每一个真相，都应该可抵达。</h1><p>检查器按照真实玩家规则取得证据，再重放结案路径。</p></div><button className="secondary" disabled={busy} onClick={onCheck}><RefreshCw size={15}/>重新检查</button></div><div className={`check-summary ${report?.passed?'passed':'failed'}`}><div className="check-symbol">{report?.passed?<ShieldCheck size={31}/>:<CircleAlert size={31}/>}</div><div><h2>{report?.passed?'案件规则可以走通':`${errors.length} 个问题阻止了完整体验`}</h2><p>{report?.passed?`已验证 ${report.reachableClues.length} 条证据，找到 ${report.winningPath.length} 步结案路径。`:'先修复不可达证据与引用错误，再导出作品。'}</p><small>{report?`检查于 ${time(report.checkedAt)} · v${project.revision}`:'尚未检查'}</small></div>{!report?.passed&&<button className="primary" onClick={onRepair} disabled={busy}><Sparkles size={16}/>让 Agent 修复</button>}</div><div className="check-metrics"><div><Check size={15}/>结构引用</div><div><GitBranch size={15}/>证据依赖</div><div><FileCheck2 size={15}/>场景可达</div><div><Play size={15}/>结案重放</div></div>{report?.issues.map((issue,i)=><div className={`issue-card ${issue.severity}`} key={i}><CircleAlert size={18}/><div><strong>{issue.message}</strong><p>{issue.path} · {issue.code}</p></div><span>{issue.severity==='error'?'待修复':'叙事审阅'}</span></div>)}<div className="verification-grid"><section className="panel"><div className="section-heading"><h3>玩家通关路径</h3><span className="muted">作者视角 · 包含剧透</span></div>{report?.winningPath.length?<ol className="path-list">{report.winningPath.map((a,i)=><li key={i}><span>{i+1}</span>{actionLabel(a)}</li>)}</ol>:<div className="empty-state">尚未找到有效通关路径。</div>}</section><section className="panel"><h3>证据依赖</h3><div className="dependency-list">{project.case.clues.map(c=><div key={c.id}><span className={`status-dot ${report?.reachableClues.includes(c.id)?'online':''}`}/><div><strong>{c.name}</strong><small>{c.sceneId?project.case.scenes.find(s=>s.id===c.sceneId)?.name:'人物证词'}{c.requires.length?` · 需要：${c.requires.map(id=>project.case.clues.find(c=>c.id===id)?.name||id).join('、')}`:' · 无额外前置条件'}</small></div></div>)}</div></section></div><div className="info-note"><CircleAlert size={17}/><p>检查通过只证明结构规则可完成。人物动机是否可信、推理是否公平、故事是否有趣，仍需作者审阅和真人试玩。</p></div><details className="diagnostic-tools"><summary>演示与诊断工具</summary><p>给一条关键物证添加“先获得自己”的条件，明确演示检查器如何发现循环依赖。操作会创建可恢复的新版本。</p><button className="secondary" disabled={busy} onClick={onInject}>注入证据死锁（演示）</button></details></>;
}
